name: Deploy Hugo site to server via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-hugo-sftp
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  TZ: Europe/Moscow
  HUGO_VERSION: 0.148.2
  DART_SASS_VERSION: 1.90.0
  HUGO_ENVIRONMENT: production
  BASE_URL: https://gurfoto.ru/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Задаём HUGO_CACHEDIR без runner.temp — через $GITHUB_ENV
      - name: Set Hugo cache dir
        run: echo "HUGO_CACHEDIR=$GITHUB_WORKSPACE/.hugo_cache" >> "$GITHUB_ENV"

      - name: Prepare local bin dir
        run: mkdir -p "$HOME/.local" "$HOME/.local/bin"

      - name: Install Dart Sass
        run: |
          curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          tar -C "$HOME/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          rm "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          echo "$HOME/.local/dart-sass" >> "$GITHUB_PATH"

      - name: Install Hugo (extended)
        run: |
          curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          mkdir -p "$HOME/.local/hugo"
          tar -C "$HOME/.local/hugo" -xf "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          rm "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          echo "$HOME/.local/hugo" >> "$GITHUB_PATH"

      - name: Verify toolchain
        run: |
          sass --version
          hugo version

      - name: Build with Hugo
        run: |
          hugo --gc --minify --baseURL "$BASE_URL"

      - name: Install rclone
        run:
