# Building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to server via FTP

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.139.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Moscow
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL https://gurfoto.ru/

      - name: Create rclone config
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf << EOF
          [sftp]
          type = sftp
          host = ${{ secrets.SFTP_HOST }}
          user = ${{ secrets.SFTP_USERNAME }}
          pass = ${{ secrets.SFTP_PASSWORD }}
          EOF

      - name: Deploy with rclone
        run: |
          rclone sync \
            "${{ secrets.SFTP_LOCAL_DIR }}" \
            "sftp:${{ secrets.SFTP_TARGET_DIR }}" \
            --exclude "/vtour/**" \
            --filter "- /vtour/**" \
            --progress \
            --stats 1s