# Building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to server via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.137.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Moscow
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL https://gurfoto.ru/

      - name: Deploy with rclone
        run: |
          rclone sync \
            ./public \
            :sftp:${{ secrets.SFTP_TARGET_DIR }} \
            --sftp-host=${{ secrets.SFTP_HOST }} \
            --sftp-user=${{ secrets.SFTP_USERNAME }} \
            --sftp-pass=${{ secrets.SFTP_PASSWORD }} \
            --exclude "/vtour/**" \
            --filter "- /vtour/**" \
            --stats 1s
